eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: login-project
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        default-label: dev
        jdbc:
          sql: Select * from User
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datawhale?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

